<../../../mkconfig

TARG=\
	canvas.dis\
	glyph.dis\
	icurses.dis\
	keymap.dis\
	msg.dis\
	paint.dis\
	text.dis\
	theme.dis\
	ui.dis\
	view.dis\

MODULES=\

SYSMODULES=\
	icurses/canvas.m\
	icurses/glyph.m\
	icurses/icurses.m\
	icurses/keymap.m\
	icurses/msg.m\
	icurses/paint.m\
	icurses/text.m\
	icurses/theme.m\
	icurses/ui.m\
	icurses/view.m\

DISBIN=$ROOT/dis/lib/icurses

<$ROOT/mkfiles/mkdis

LIMBOFLAGS= -c $LIMBOFLAGS
